/**
 * AUTOGENERATED FROM synap/sdk/CONTRACT/endpoints.yaml -- DO NOT EDIT.
 * Regenerate with synap/sdk/scripts/sync-contract.sh.
 *
 * The /api/v1 vs /v1 prefix split is intentional and load-bearing. See the
 * contract file: normalising it 404s every affected call in production.
 */

export interface EndpointSpec {
  readonly method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS';
  readonly path: string;
  /**
   * Whether a retry after an ambiguous failure is safe.
   *
   * False here means a retry can double-ingest and therefore double-bill.
   * See defect D / gotcha G-L in the migration plan.
   */
  readonly idempotent: boolean;
}

export const ENDPOINTS = {
  whoami: { method: "GET", path: "/api/v1/auth/whoami", idempotent: true },
  memories_create: { method: "POST", path: "/api/v1/memories/create", idempotent: false },
  memories_batch: { method: "POST", path: "/api/v1/memories/batch", idempotent: false },
  memories_upload: { method: "POST", path: "/api/v1/memories/upload", idempotent: false },
  memories_status: { method: "GET", path: "/api/v1/memories/status/{ingestion_id}", idempotent: true },
  memories_get: { method: "GET", path: "/api/v1/memories/{memory_id}", idempotent: true },
  memories_update: { method: "PATCH", path: "/api/v1/memories/{memory_id}", idempotent: false },
  memories_delete: { method: "DELETE", path: "/api/v1/memories/{memory_id}", idempotent: true },
  context_fetch_user: { method: "POST", path: "/v1/context/user/fetch", idempotent: true },
  context_fetch_customer: { method: "POST", path: "/v1/context/customer/fetch", idempotent: true },
  context_fetch_client: { method: "POST", path: "/v1/context/client/fetch", idempotent: true },
  context_fetch_conversation: { method: "POST", path: "/v1/context/conversation/fetch", idempotent: true },
  context_for_prompt: { method: "GET", path: "/v1/conversations/{conversation_id}/context-for-prompt", idempotent: true },
  conversations_ingest: { method: "POST", path: "/v1/conversations/ingest", idempotent: false },
  conversations_messages: { method: "POST", path: "/v1/conversations/messages", idempotent: false },
  conversations_messages_batch: { method: "POST", path: "/v1/conversations/messages/batch", idempotent: false },
  conversations_compact: { method: "POST", path: "/v1/conversations/compact", idempotent: false },
  conversations_compacted: { method: "GET", path: "/v1/conversations/{conversation_id}/compacted", idempotent: true },
  conversations_compaction_status: { method: "GET", path: "/v1/conversations/{conversation_id}/compaction/status", idempotent: true },
  user_profile: { method: "GET", path: "/v1/users/{user_id}/profile", idempotent: true },
  credits_balance: { method: "GET", path: "/v1/credits/balance", idempotent: true },
  credits_ledger: { method: "GET", path: "/v1/credits/ledger", idempotent: true },
  credits_estimate: { method: "POST", path: "/v1/credits/estimate", idempotent: true },
  credits_redeem: { method: "POST", path: "/v1/credits/redeem", idempotent: false },
  telemetry_batch: { method: "POST", path: "/v1/telemetry/batch", idempotent: false },
} as const satisfies Record<string, EndpointSpec>;

export type EndpointName = keyof typeof ENDPOINTS;

/** Substitute `{placeholder}` segments. Values are URL-encoded.
 *
 * Encoding matters: an unencoded id containing `/` or `?` silently
 * retargets the request at a different route.
 */
export function resolvePath(
  name: EndpointName,
  params: Readonly<Record<string, string | number>> = {},
): string {
  return ENDPOINTS[name].path.replace(/\{(\w+)\}/g, (_m, key: string) => {
    const value = params[key];
    if (value === undefined || value === null || value === '') {
      throw new Error(
        `Endpoint ${name} requires path parameter '${key}'.`,
      );
    }
    return encodeURIComponent(String(value));
  });
}
