# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import synap_service_pb2 as synap__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in synap_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SynapServiceStub(object):
    """=============================================================================
    Service Definition
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Listen = channel.stream_stream(
                '/synap.v1.SynapService/Listen',
                request_serializer=synap__service__pb2.StreamEvent.SerializeToString,
                response_deserializer=synap__service__pb2.StreamResponse.FromString,
                _registered_method=True)
        self.IngestTelemetry = channel.stream_unary(
                '/synap.v1.SynapService/IngestTelemetry',
                request_serializer=synap__service__pb2.TelemetryEvent.SerializeToString,
                response_deserializer=synap__service__pb2.TelemetryAck.FromString,
                _registered_method=True)


class SynapServiceServicer(object):
    """=============================================================================
    Service Definition
    =============================================================================

    """

    def Listen(self, request_iterator, context):
        """Bidirectional stream: SDK sends conversation events, server sends back
        anticipatory context bundles and control signals.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestTelemetry(self, request_iterator, context):
        """Client-streaming: SDK sends telemetry events in a stream, server
        acknowledges once when the client closes its half.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SynapServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Listen': grpc.stream_stream_rpc_method_handler(
                    servicer.Listen,
                    request_deserializer=synap__service__pb2.StreamEvent.FromString,
                    response_serializer=synap__service__pb2.StreamResponse.SerializeToString,
            ),
            'IngestTelemetry': grpc.stream_unary_rpc_method_handler(
                    servicer.IngestTelemetry,
                    request_deserializer=synap__service__pb2.TelemetryEvent.FromString,
                    response_serializer=synap__service__pb2.TelemetryAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'synap.v1.SynapService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('synap.v1.SynapService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SynapService(object):
    """=============================================================================
    Service Definition
    =============================================================================

    """

    @staticmethod
    def Listen(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/synap.v1.SynapService/Listen',
            synap__service__pb2.StreamEvent.SerializeToString,
            synap__service__pb2.StreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestTelemetry(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/synap.v1.SynapService/IngestTelemetry',
            synap__service__pb2.TelemetryEvent.SerializeToString,
            synap__service__pb2.TelemetryAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
