"""AUTOGENERATED FROM synap/sdk/CONTRACT/endpoints.yaml -- DO NOT EDIT.
Regenerate with synap/sdk/scripts/sync-contract.sh.

The /api/v1 vs /v1 prefix split is intentional and load-bearing. See the
contract file: normalising it 404s every affected call in production."""

from typing import Dict, Final

ENDPOINTS: Final[Dict[str, Dict[str, object]]] = {
    "whoami": {"method": "GET", "path": "/api/v1/auth/whoami", "idempotent": True},
    "memories_create": {"method": "POST", "path": "/api/v1/memories/create", "idempotent": False},
    "memories_batch": {"method": "POST", "path": "/api/v1/memories/batch", "idempotent": False},
    "memories_upload": {"method": "POST", "path": "/api/v1/memories/upload", "idempotent": False},
    "memories_status": {"method": "GET", "path": "/api/v1/memories/status/{ingestion_id}", "idempotent": True},
    "memories_get": {"method": "GET", "path": "/api/v1/memories/{memory_id}", "idempotent": True},
    "memories_update": {"method": "PATCH", "path": "/api/v1/memories/{memory_id}", "idempotent": False},
    "memories_delete": {"method": "DELETE", "path": "/api/v1/memories/{memory_id}", "idempotent": True},
    "context_fetch_user": {"method": "POST", "path": "/v1/context/user/fetch", "idempotent": True},
    "context_fetch_customer": {"method": "POST", "path": "/v1/context/customer/fetch", "idempotent": True},
    "context_fetch_client": {"method": "POST", "path": "/v1/context/client/fetch", "idempotent": True},
    "context_fetch_conversation": {"method": "POST", "path": "/v1/context/conversation/fetch", "idempotent": True},
    "context_for_prompt": {"method": "GET", "path": "/v1/conversations/{conversation_id}/context-for-prompt", "idempotent": True},
    "conversations_ingest": {"method": "POST", "path": "/v1/conversations/ingest", "idempotent": False},
    "conversations_messages": {"method": "POST", "path": "/v1/conversations/messages", "idempotent": False},
    "conversations_messages_batch": {"method": "POST", "path": "/v1/conversations/messages/batch", "idempotent": False},
    "conversations_compact": {"method": "POST", "path": "/v1/conversations/compact", "idempotent": False},
    "conversations_compacted": {"method": "GET", "path": "/v1/conversations/{conversation_id}/compacted", "idempotent": True},
    "conversations_compaction_status": {"method": "GET", "path": "/v1/conversations/{conversation_id}/compaction/status", "idempotent": True},
    "user_profile": {"method": "GET", "path": "/v1/users/{user_id}/profile", "idempotent": True},
    "credits_balance": {"method": "GET", "path": "/v1/credits/balance", "idempotent": True},
    "credits_ledger": {"method": "GET", "path": "/v1/credits/ledger", "idempotent": True},
    "credits_estimate": {"method": "POST", "path": "/v1/credits/estimate", "idempotent": True},
    "credits_redeem": {"method": "POST", "path": "/v1/credits/redeem", "idempotent": False},
    "telemetry_batch": {"method": "POST", "path": "/v1/telemetry/batch", "idempotent": False},
}
